[2024-10-03T23:03:39.137-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T23:03:42.651-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:57:09.080078+00:00 [queued]>
[2024-10-03T23:03:42.822-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:57:09.080078+00:00 [queued]>
[2024-10-03T23:03:42.824-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-03T23:03:43.082-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): upload_pdfs_task> on 2024-10-04 02:57:09.080078+00:00
[2024-10-03T23:03:43.086-0400] {standard_task_runner.py:72} INFO - Started process 38201 to run task
[2024-10-03T23:03:43.088-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'huggingface_pdf_pipeline', 'upload_pdfs_task', 'manual__2024-10-04T02:57:09.080078+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/huggingface_pdf_airflow_dag.py', '--cfg-path', '/tmp/tmpjov99yqr']
[2024-10-03T23:03:43.090-0400] {standard_task_runner.py:105} INFO - Job 52: Subtask upload_pdfs_task
[2024-10-03T23:03:52.644-0400] {job.py:229} INFO - Heartbeat recovered after 36.12 seconds
[2024-10-03T23:03:55.312-0400] {task_command.py:467} INFO - Running <TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:57:09.080078+00:00 [running]> on host LAPTOP-GD5THE3N.
[2024-10-03T23:04:16.501-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='huggingface_pdf_pipeline' AIRFLOW_CTX_TASK_ID='upload_pdfs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T02:57:09.080078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T02:57:09.080078+00:00'
[2024-10-03T23:04:16.509-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-03T23:04:16.511-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-03T23:04:16.513-0400] {logging_mixin.py:190} INFO - Current task name:upload_pdfs_task state:running start_date:2024-10-04 03:03:42.655826+00:00
[2024-10-03T23:04:16.515-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline and current dag run status:running
[2024-10-03T23:04:16.516-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T23:04:16.518-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T23:04:16.522-0400] {logging_mixin.py:190} INFO - Error uploading h to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'h'
[2024-10-03T23:04:16.524-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T23:04:16.525-0400] {logging_mixin.py:190} INFO - Error uploading m to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'm'
[2024-10-03T23:04:16.527-0400] {logging_mixin.py:190} INFO - Error uploading e to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'e'
[2024-10-03T23:04:16.529-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T23:04:16.531-0400] {logging_mixin.py:190} INFO - Error uploading p to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'p'
[2024-10-03T23:04:16.532-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T23:04:16.534-0400] {logging_mixin.py:190} INFO - Error uploading t to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 't'
[2024-10-03T23:04:16.536-0400] {logging_mixin.py:190} INFO - Error uploading r to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'r'
[2024-10-03T23:04:16.537-0400] {logging_mixin.py:190} INFO - Error uploading i to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'i'
[2024-10-03T23:04:16.539-0400] {logging_mixin.py:190} INFO - Error uploading c to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'c'
[2024-10-03T23:04:16.541-0400] {logging_mixin.py:190} INFO - Error uploading k to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'k'
[2024-10-03T23:04:16.543-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T23:04:16.545-0400] {logging_mixin.py:190} INFO - Error uploading D to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'D'
[2024-10-03T23:04:16.547-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T23:04:16.549-0400] {logging_mixin.py:190} INFO - Error uploading w to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'w'
[2024-10-03T23:04:16.551-0400] {logging_mixin.py:190} INFO - Error uploading n to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'n'
[2024-10-03T23:04:16.552-0400] {logging_mixin.py:190} INFO - Error uploading l to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'l'
[2024-10-03T23:04:16.554-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T23:04:16.556-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T23:04:16.559-0400] {logging_mixin.py:190} INFO - Error uploading d to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'd'
[2024-10-03T23:04:16.561-0400] {logging_mixin.py:190} INFO - Error uploading s to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 's'
[2024-10-03T23:04:16.563-0400] {python.py:240} INFO - Done. Returned value was: None
[2024-10-03T23:04:19.524-0400] {job.py:229} INFO - Heartbeat recovered after 26.98 seconds
[2024-10-03T23:04:36.671-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T23:04:36.674-0400] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=huggingface_pdf_pipeline, task_id=upload_pdfs_task, run_id=manual__2024-10-04T02:57:09.080078+00:00, execution_date=20241004T025709, start_date=20241004T030342, end_date=20241004T030436
[2024-10-03T23:04:37.421-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-03T23:04:37.422-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-03T23:04:37.424-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline queued_at:2024-10-04 02:57:09.809367+00:00
[2024-10-03T23:04:37.425-0400] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-GD5THE3N. operator:PythonOperator
[2024-10-03T23:04:37.876-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-03T23:04:38.149-0400] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-03T23:04:47.562-0400] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-03T23:04:47.610-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
