[2024-10-03T22:28:17.576-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T22:28:32.679-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:24:10.297091+00:00 [queued]>
[2024-10-03T22:28:32.896-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:24:10.297091+00:00 [queued]>
[2024-10-03T22:28:32.902-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-03T22:28:33.121-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): upload_pdfs_task> on 2024-10-04 02:24:10.297091+00:00
[2024-10-03T22:28:33.129-0400] {standard_task_runner.py:72} INFO - Started process 28484 to run task
[2024-10-03T22:28:33.132-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'huggingface_pdf_pipeline', 'upload_pdfs_task', 'manual__2024-10-04T02:24:10.297091+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/huggingface_pdf_airflow_dag.py', '--cfg-path', '/tmp/tmpy9t42v6b']
[2024-10-03T22:28:33.134-0400] {standard_task_runner.py:105} INFO - Job 33: Subtask upload_pdfs_task
[2024-10-03T22:28:46.878-0400] {job.py:229} INFO - Heartbeat recovered after 51.01 seconds
[2024-10-03T22:28:54.938-0400] {task_command.py:467} INFO - Running <TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:24:10.297091+00:00 [running]> on host LAPTOP-GD5THE3N.
[2024-10-03T22:29:02.075-0400] {job.py:229} INFO - Heartbeat recovered after 15.28 seconds
[2024-10-03T22:29:09.055-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='huggingface_pdf_pipeline' AIRFLOW_CTX_TASK_ID='upload_pdfs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T02:24:10.297091+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T02:24:10.297091+00:00'
[2024-10-03T22:29:09.059-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-03T22:29:09.061-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-03T22:29:09.063-0400] {logging_mixin.py:190} INFO - Current task name:upload_pdfs_task state:running start_date:2024-10-04 02:28:32.681957+00:00
[2024-10-03T22:29:09.065-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline and current dag run status:running
[2024-10-03T22:29:09.067-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T22:29:09.070-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:29:09.073-0400] {logging_mixin.py:190} INFO - Error uploading h to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'h'
[2024-10-03T22:29:09.076-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:29:09.078-0400] {logging_mixin.py:190} INFO - Error uploading m to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'm'
[2024-10-03T22:29:09.081-0400] {logging_mixin.py:190} INFO - Error uploading e to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'e'
[2024-10-03T22:29:09.082-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:29:09.083-0400] {logging_mixin.py:190} INFO - Error uploading p to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'p'
[2024-10-03T22:29:09.085-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T22:29:09.086-0400] {logging_mixin.py:190} INFO - Error uploading t to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 't'
[2024-10-03T22:29:09.088-0400] {logging_mixin.py:190} INFO - Error uploading r to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'r'
[2024-10-03T22:29:09.090-0400] {logging_mixin.py:190} INFO - Error uploading i to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'i'
[2024-10-03T22:29:09.093-0400] {logging_mixin.py:190} INFO - Error uploading c to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'c'
[2024-10-03T22:29:09.095-0400] {logging_mixin.py:190} INFO - Error uploading k to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'k'
[2024-10-03T22:29:09.096-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:29:09.097-0400] {logging_mixin.py:190} INFO - Error uploading D to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'D'
[2024-10-03T22:29:09.097-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:29:09.098-0400] {logging_mixin.py:190} INFO - Error uploading w to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'w'
[2024-10-03T22:29:09.099-0400] {logging_mixin.py:190} INFO - Error uploading n to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'n'
[2024-10-03T22:29:09.100-0400] {logging_mixin.py:190} INFO - Error uploading l to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'l'
[2024-10-03T22:29:09.101-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:29:09.101-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T22:29:09.102-0400] {logging_mixin.py:190} INFO - Error uploading d to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'd'
[2024-10-03T22:29:09.103-0400] {logging_mixin.py:190} INFO - Error uploading s to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 's'
[2024-10-03T22:29:09.103-0400] {python.py:240} INFO - Done. Returned value was: None
[2024-10-03T22:29:12.142-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T22:29:12.145-0400] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=huggingface_pdf_pipeline, task_id=upload_pdfs_task, run_id=manual__2024-10-04T02:24:10.297091+00:00, execution_date=20241004T022410, start_date=20241004T022832, end_date=20241004T022912
[2024-10-03T22:29:12.396-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-03T22:29:12.399-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-03T22:29:12.402-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline queued_at:2024-10-04 02:24:11.104549+00:00
[2024-10-03T22:29:12.404-0400] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-GD5THE3N. operator:PythonOperator
[2024-10-03T22:29:12.450-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-03T22:29:13.180-0400] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-03T22:29:18.172-0400] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-03T22:29:18.231-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
